src/Entity/Game.php
<?php

namespace App\Entity;

use App\Entity\ValueObject\Result;
use PChess\Chess\Chess;
use PChess\Chess\Move;
use PChess\Chess\Piece;
use PChess\ChessBundle\Mover;
use Ramsey\Uuid\UuidInterface;

class Game
{
    private string $fen;

    /** @var array<int, string> */
    private array $history;

    private ?Player $black = null;

    private ?Player $white = null;

    public function __construct(
        private UuidInterface $id,
        Player $player,
        string $color = 'w',
        Chess $chess = new Chess(),
        private ?\DateTimeImmutable $start = null,
        private ?\DateTimeImmutable $end = null,
        private ?\DateTimeImmutable $lastMove = null,
        private ?Result $result = null,
    ) {
        $this->fen = $chess->fen();
        $this->history = Mover::getHistoryStrings($chess);
        if ('w' === $color) {
            $this->white = $player;
        } else {
            $this->black = $player;
        }
    }

    public function join(Player $player, string $color): void
    {
        if ('w' === $color) {
            $this->whiteJoin($player);
        } else {
            $this->blackJoin($player);
        }
    }

    public function blackJoin(Player $player): void
    {
        if (null !== $this->black) {
            throw new \DomainException('Black already joined.');
        }
        $this->black = $player;
    }

    public function whiteJoin(Player $player): void
    {
        if (null !== $this->white) {
            throw new \DomainException('White already joined.');
        }
        $this->white = $player;
    }

    public function isWhitePlayer(Player $player): bool
    {
        return null !== $this->white && $this->white->getId()->equals($player->getId());
    }

    public function isBlackPlayer(Player $player): bool
    {
        return null !== $this->black && $this->black->getId()->equals($player->getId());
    }

    public function resign(Player $resigningPlayer): void
    {
        $this->end = new \DateTimeImmutable();
        $this->result = $this->isBlackPlayer($resigningPlayer) ? Result::WHITE_WON : Result::BLACK_WON;
    }

    public function getId(): UuidInterface
    {
        return $this->id;
    }

    public function getChess(?Player $player = null): Chess
    {
        $chess = new Chess($this->fen, Mover::getHistoryEntries($this->history));
        if (null !== $player && $this->isBlackPlayer($player)) {
            $chess->board->reverse();
        }

        return $chess;
    }

    public function move(string $from, string $to, ?string $promotion): ?Move
    {
        $chess = $this->getChess();
        $move = $chess->move(['from' => $from, 'to' => $to, 'promotion' => $promotion]);
        $this->setChess($chess);
        if ($chess->gameOver()) {
            if ($chess->inStalemate() || $chess->inDraw()) {
                $this->draw();
            } elseif ($chess->inCheckmate()) {
                $this->win();
            }
        }

        return $move;
    }

    private function setChess(Chess $chess): void
    {
        if (null === $this->start) {
            $this->start = new \DateTimeImmutable();
        }
        $this->lastMove = new \DateTimeImmutable();
        $this->fen = $chess->fen();
        $this->history = Mover::getHistoryStrings($chess);
    }

    public function getBlack(): ?Player
    {
        return $this->black;
    }

    public function getWhite(): ?Player
    {
        return $this->white;
    }

    public function getStart(): ?\DateTimeImmutable
    {
        return $this->start;
    }

    public function getLastMove(): ?\DateTimeImmutable
    {
        return $this->lastMove;
    }

    public function getEnd(): ?\DateTimeImmutable
    {
        return $this->end;
    }

    public function getResult(): ?Result
    {
        return $this->result;
    }

    public function isStarted(): bool
    {
        return null !== $this->start;
    }

    public function isEnded(): bool
    {
        return null !== $this->end;
    }

    private function draw(): void
    {
        $this->end = new \DateTimeImmutable();
        $this->result = Result::DRAW;
    }

    private function win(): void
    {
        $this->end = new \DateTimeImmutable();
        $this->result = Piece::WHITE === $this->getChess()->turn ? Result::WHITE_WON : Result::BLACK_WON;
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Repository\GameRepository;
use App\Repository\PlayerRepository;
use Ramsey\Uuid\Uuid;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/game/', name: 'game_')]
final class GameController extends AbstractController
{
    #[Route(path: 'new/{color}', name: 'new', methods: 'GET')]
    public function new(string $color, GameRepository $repoGame, PlayerRepository $repoPlayer): Response
    {
        if (null === $player = $repoPlayer->findByEmail($this->getUserEmail())) {
            throw $this->createAccessDeniedException();
        }
        $game = new Game(Uuid::uuid4(), $player, $color);
        $repoGame->add($game);

        return $this->redirectToRoute('game_show', ['id' => $game->getId()]);
    }

    #[Route(path: '{id}', name: 'show', methods: 'GET')]
    public function game(string $id, GameRepository $repoGame): Response
    {
        $game = $repoGame->get($id);

        return $this->render('game/game.html.twig', ['id' => $id, 'game' => $game]);
    }

    #[Route(path: '{id}/join/{color}', name: 'join', methods: 'GET')]
    public function join(string $id, string $color, GameRepository $repoGame, PlayerRepository $repoPlayer): Response
    {
        if (null === $player = $repoPlayer->findByEmail($this->getUserEmail())) {
            throw $this->createAccessDeniedException();
        }
        $game = $repoGame->get($id);
        $game->join($player, $color);
        $repoGame->add($game);

        return $this->redirectToRoute('game_show', ['id' => $id]);
    }

    #[Route(path: '{id}/resign', name: 'resign', methods: 'GET')]
    public function resign(string $id, GameRepository $repoGame, PlayerRepository $repoPlayer): Response
    {
        $game = $repoGame->get($id);
        $this->denyAccessUnlessGranted('resign', $game);
        $game->resign($repoPlayer->getByEmail($this->getUserEmail()));
        $repoGame->add($game);

        return $this->redirectToRoute('game_show', ['id' => $id]);
    }

    private function getUserEmail(): string
    {
        if (null === $user = $this->getUser()) {
            throw $this->createAccessDeniedException();
        }

        return $user->getUserIdentifier();
    }
}

templates/game/game.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ parent() }} - game {{ game.id }}{% endblock %}

{% set player = player() %}
{% set chess = game.chess(player) %}

{% block body %}
    <div class="row">
        <div class="col-12 col-lg-9">
            {{ chess_render(chess, from|default(null), id) }}
            <p class="text-center text-muted d-none d-md-inline-block">{{ chess.fen }}</p>
        </div>
        <div class="col-12 col-lg-3">
            {% if game.start %}
                Started: {{ game.start|date('Y-m-d H:i') }}
            {% endif %}
            {% if game.lastMove %}
                <br>Updated: {{ game.lastMove|date('Y-m-d H:i') }}
            {% endif %}

            <div class="pl-white player{{ game.start and chess.turn == 'w' ? ' fw-bold' : '' }}">
                {% if game.white %}
                    {{ game.white }}
                    <img class="rounded-circle" src="{{ game.white.avatar ?? asset('square.png') }}" alt="">
                {% elseif game.blackPlayer(player) %}
                    waiting for opponent...
                {% else %}
                    <a href="{{ path('game_join', {id: game.id, color: 'w'}) }}" class="btn btn-light btn-sm">join</a>
                {% endif %}
            </div>
            <div class="pl-black player{{ chess.turn == 'b' ? ' fw-bold' : '' }}">
                {% if game.black %}
                    {{ game.black }}
                    <img class="rounded-circle" src="{{ game.black.avatar ?? asset('square.png') }}" alt="">
                {% elseif game.whitePlayer(player) %}
                    waiting for opponent...
                {% else %}
                    <a href="{{ path('game_join', {id: game.id, color: 'b'}) }}" class="btn btn-light btn-sm">join</a>
                {% endif %}
            </div>

            {% if game.started and not game.ended %}
                <p>Turn: {{ chess.turn == 'b' ? 'black' : 'white' }}</p>
            {% endif %}

            {% if game.started and chess.history|length %}
                <h3>History</h3>
                <ol>
                    <li>
                        {%- for num, history in chess.history.entries -%}
                            {{ history }} {{ num % 2 ? '</li><li>' }}
                        {%- endfor -%}
                    </li>
                </ol>
                {#
                <a href="{{ path('move_undo', {id: id}) }}" class="btn btn-warning d-print-none">
                    <i class="fas fa-arrow-left"></i> undo
                </a>
                #}
            {% endif %}

            {% if game.ended %}
                <h3>Game over</h3>
                {{ game.result.label }}
                {% if chess.inCheckmate %}
                    check mate
                {% elseif chess.inStalemate %}
                    stale mate
                {% elseif chess.inDraw %}
                    draw
                {% endif %}
            {% elseif to is defined %}
                <h3>Promote to</h3>
                <div id="promotions">
                    {% for piece in ['q', 'r', 'n', 'b'] %}
                        <a class="{{ chess.turn }}{{ piece }}" href="{{ path('move_end', {id: id, from: from, to: to, promotion: piece}) }}"></a>
                    {% endfor %}
                </div>
            {% elseif from is defined %}
                <h3>Possible moves</h3>
                <ul class="list-unstyled">
                    {% for square, squareMoves in moves %}
                        {% for move in squareMoves %}
                            <li>{{ square }} {{ move }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
            {% if game.started and not game.ended %}
                <a href="{{ path('game_resign', {id: game.id}) }}" onclick="return confirm('Are you sure you want to resign?')">
                    resign
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/game/index.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    <table class="table table-hover">
        <thead class="dark">
            <tr>
                <th scope="col"></th>
                <th scope="col">White</th>
                <th scope="col">Black</th>
                <th scope="col" class="d-none d-md-table-cell">Start</th>
                <th scope="col">Last</th>
                <th class="d-none d-md-table-cell">End</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for game in games %}
                <tr>
                    <td>
                        <img src="{{ image(game.chess) }}" alt="">
                    </td>
                    <td>
                        <span{{ game.start and game.chess.turn == 'w' ? ' class="fw-bold"' : '' }}>
                            {{ game.white|default('-') }}
                        </span>
                    </td>
                    <td>
                        <span{{ game.chess.turn == 'b' ? ' class="fw-bold"' : '' }}>
                            {{ game.black|default('-') }}
                        </span>
                    </td>
                    <td class="d-none d-md-table-cell">
                        {{ game.start ? game.start|date('Y-m-d H:i') : '-' }}
                    </td>
                    <td>
                        {{ game.lastMove ? game.lastMove|date('Y-m-d H:i') : '-' }}
                    </td>
                    <td class="d-none d-md-table-cell">
                        {{ game.end ? game.end|date('Y-m-d H:i') : '-' }}
                    </td>
                    <td>
                        <a href="{{ path('game_show', {id: game.id}) }}" class="btn btn-secondary">
                            view
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">No active game at the moment.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="btn-group">
        <button class="btn btn-primary btn-lg" disabled>start <span class="d-none d-md-inline">new</span> game as</button>
        <a class="btn btn-light btn-lg" href="{{ path('game_new', {color: 'w'}) }}">white</a>
        <a class="btn btn-dark btn-lg" href="{{ path('game_new', {color: 'b'}) }}">black</a>
    </div>
{% endblock %}